#Name of Eureka_Registery application
spring:
  application:
    name: eureka-discovery-service

#Eureka_Registery server run on given port
server:
  port: 8085
  
#  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
    serviceUrl:
      defaultZone: http://localhost:8085/eureka 