server:
  port: 8090

spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:8088
        predicates:
        - Path=/student/**
        
      - id: courseModule
        uri: http://localhost:8084
        predicates:
        - Path=/course/**