server:
  port: 8090

spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:8088
        predicates:
        - Path=/student/**  #Anything with this uri move to above route
        
      - id: courseModule
        uri: http://localhost:8084
        predicates:
        - Path=/course/**   #Anything with this uri move to above route
        filters:
        - name: Requestsize
          args:
            maxSize: 5000000 #the request size can not be more than tis byte(default)